### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#1]
As a blockchain developer, I want Koinos built on all supported compilers and the units tests ran automatically, so that I can have assurance that my new code does not break any existing features.

**Supported compilers:**
GCC, Clang

**Supported environments:**
Ubuntu 18.04, 20.04 64-bit/x86
macOS (latest)

**Tasks:**
- [x] Determine which CI platform to integrate with #2 
- [x] Write the necessary CI script files (e.g. .travis.yml) #3 
- [X] Integrate with GitHub project #4 
- [X] Document the process for creating CI for use in other projects #5
