### ISSUE TITLE
Smart Contract System Calls

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#161]
As a smart contract developer, I want to call Koinos system calls using native C++ functions from my C++ smart contract.

- [x] Update Koinos Type naming and namespaces (#163)
- [x] Create Koinos Types repo and make it a submodule of Koinos (#162)
- [x] Move pack tests in to Koinos Types (#164)
- [x] Create Koinos C++ CDT Repo (#165)
- [x] Statically link libc++ for CDT (#166)
- [x] Create C++ wrappers for all currently defined system calls (open-orchard/koinos-cdt#2)
