### ISSUE TITLE
PoW Smart Contract

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#210]
As a Koinos user, I want a fair and equitable launch of Koinos using a PoW mining algorithm for block production.

- [x] Create a thunk that returns the block height and current id (implement `get_head_info` as a thunk). (#212)
- [x] `passive_block_data` should just contain a `variable_blob` that is deserialized by `verify_block_header` to allow changing between different serializations in consensus. The original `initminer` signature serialization should be maintained for genesis. `verify_block_header` should receive all bytes of the passive data and the digest of the active bytes. (#213)
- [x] Write a hash system call that exposes the multihash interface. The thunk should validate the hash id against a fixed set of accepted hash algorithm ids to facilitate proper upgrade semantics. (#214)
- [x] Create a system call contract that overrides `verify_block_header` which instead validates a proof against a static difficulty. (#215)
- [x] Update `block_producer_plugin.cpp` that mines proofs in a separate thread. (#216)
