### ISSUE TITLE
Block Generation

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#22]
As a blockchain developer, I want to generate and push new blocks.
- [x] Add a debug "state" for testing, that just holds the head block ID for state manipulation tests #40
- [x] Push the block to the correct fork #39 
- [x] A block producer plugin #41
