### ISSUE TITLE
Opaque Types

### ISSUE THREAD

**Issue by brklyn8900** [koinos/koinos-chain#225]
As a Koinos developer, I would like to manipulate opaque data types with ease. 

- [x] Implement opaque type that explicitly enforces unboxing and access while allowing a native syntax to underlying access. #231
- [x] Require contained opaque types to be versioned via `std::variant`. #232
- [x] ~~Audit existing schema to determine what type should be opaque. (requires parking lot)  #233~~
- [x] Update Koinos to use opaque type. #234
- [x] Test opaque type in Koinos types. #235
