### ISSUE TITLE
Koinosd JSON RPC

### ISSUE THREAD

**Issue by brklyn8900** [koinos/koinos-chain#227]
As a blockchain engineer, I want an implementation of JSON RPC so that I can talk to microservices.

- [x] Create server implementation (in koinos::net::jsonrpc) (#254)
- [ ] Create client implementation (in koinos::net::jsonrpc) (#255)
- [ ] Create plugin that wraps the server implementation and initialize via config options (#256)
- [x] Create API registration interface in the plugin (#257)
