### ISSUE TITLE
RabbitMQ Implementation

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#277]
As a blockchain daemon, I would like to consume messages from the peer to peer network and API nodes.

- [x] Create a C++ wrapper implementation for `rabbitmq-c` that allows for the **publication** of messages. (#278)
- [x] Create a C++ wrapper implementation for `rabbitmq-c` that allows for the **consumption** of messages with callbacks to handle individual message types. (#279)
- [x] Create a message consumer. (#281)
- [x] Produce a message on to a queue when a block application is successful. (#282)
