### ISSUE TITLE
Read-only smart contract calls

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#313]
As a blockchain user, I would like to query the state of smart contracts.

- [x] Add a `read-only` flag to the apply context and return an error if the user calls `db_put_object` with this flag `true`. (Check other thunk implementations to ensure that nothing else writes to the database) (#383)
- [x] Add a `chain_rpc` type called `read_contract_request`/`read_contract_response` that should mirror `contract_call_operation` without the extensions. `read_contract_response` should have an additional field `logs` that contains the `console_log` output from the contract execution (koinos/koinos-types#183)
- [x] Implement the API call `read_contract_request` (#384)
