### ISSUE TITLE
Transaction signing tool

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#329]
As a blockchain user, I want a standalone application to sign transactions and write them to STDOUT.

- [x] Create a program in `./programs/sign_transaction` (#334)
- [x] Accept JSON transaction through STDIN (#335)
- [x] Program argument can be specified for private key file `--private-key,k` (#336)
- [x] Specify a flag to wrap the resulting transaction in a `submit_transaction_request ` --> `--wrap,w` (#337)

**Note:**
The wrapping should be a `chain_rpc_request` variant that is a `submit_transaction_request`

**Example: **
`cat transaction.json | sign_transaction`
