### ISSUE TITLE
Smart Contract API

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#34]
As a smart contract developer, I would like to upload and execute my own custom code.

- [x] Stub out all the following system calls, `apply_block`, `apply_transaction`, `apply_upload_contract_operation`, and `apply_execute_contract_operation`. Also stub out the arguments and return values for each new system call. #125
- [x] Disable all EOS related database calls (through comments) and disable `vm_test.cpp` #126
- [x] Implement statedb wrapper system calls #127
- [x] Implement an `apply_block` system call #128 
- [x] Implement an `apply_transaction` system call #129 
- [x] Implement an `apply_upload_contract_operation` system call #130 
- [x] Implement an `apply_execute_contract_operation` system call #131 
- [x] Enable `vm_test.cpp` with our demo wasm file #133 
- [x] On a **_throw away_** demo branch, hack block_producer plugin to upload and execute the demo smart contract #134 

**Deliverable:** Ensure this simple contract compiles and executes on chain.
```
#include <koinos/koinos.hpp>

using namespace koinos;

class [[koinos::contract]] hello : public contract {
  public:
      using contract::contract;

      void hi( name user ) {
         print( "Hello, ", user);
      }
};
```
