### ISSUE TITLE
Transaction Reversions

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-chain#406]
As a blockchain engineer, I would like to prevent abuse on my beloved chain.

- [x] Extend the state node to allow for creation of anonymous child nodes (#416)
- [x] Create anonymous state node children upon transaction application (#417)
- [x] Squash anonymous child node if the transaction was applied successfully and discard if it does not (#418)
