### ISSUE TITLE
Merge ForkDB and StateDB

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#82]
As a developer, I want a unified interface for applying state changes to a specific state node.

In #39, the controller keeps state db and fork db in sync with one another. With positive state deltas, management of undo states no longer needs to be handled as a stack (as in chainbase) but can be a a tree (like StateDB and the fork db). This functionality should be abstracted and handled by a single library.

- [x] Fix StateDB PascalCase naming (#89)
- [x] Move fork handling logic from fork_db and positive delta code from chainbase in to state_db. The fork logic will own the positive deltas as a tree instead of a stack. `get_node` and `create_writable_node` encapsulate the entire fork interface needed by controller. (#90)
- [x] Refactor fork_db tests to use state_db (#91) 
- [x] Test pushing blocks to a minority fork (as described in #39) (#92)
- [x] Add statedb tests (#93)
- [x] Remove chainbase and fork_db (#94)
- [x] Remove statedb/include/stun (#95)
